<?php
session_start();

// Include config file
include('../config.php');

// Include PHPExcel
require_once '../PHPExcel/PHPExcel.php';

// Function to export data to Excel (XLSX)
function exportToExcel($conn) {
    try {
        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        // Set document properties
        $objPHPExcel->getProperties()->setCreator("Your Name")
                                     ->setLastModifiedBy("Your Name")
                                     ->setTitle("Transaction Report")
                                     ->setSubject("Transaction Data")
                                     ->setDescription("Transaction report generated by PHPExcel.")
                                     ->setKeywords("office PHPExcel php")
                                     ->setCategory("Transaction Report");

        // Add data from database
        $query = "SELECT * FROM Transaksi";
        $result = $conn->query($query);

        // Set active sheet
        $objPHPExcel->setActiveSheetIndex(0);
        $sheet = $objPHPExcel->getActiveSheet();

        // Set headers
        $sheet->setCellValue('A1', 'ID');
        $sheet->setCellValue('B1', 'Warga ID');
        $sheet->setCellValue('C1', 'Jumlah');
        $sheet->setCellValue('D1', 'Tanggal');
        $sheet->setCellValue('E1', 'Jenis Transaksi');

        // Fill data rows
        $row = 2;
        while ($row_data = $result->fetch_assoc()) {
            $sheet->setCellValue('A' . $row, $row_data['id']);
            $sheet->setCellValue('B' . $row, $row_data['warga_id']);
            $sheet->setCellValue('C' . $row, $row_data['jumlah']);
            $sheet->setCellValue('D' . $row, $row_data['tanggal']);
            $sheet->setCellValue('E' . $row, $row_data['jenis_transaksi']);
            $row++;
        }

        // Set header columns width autosize
        foreach(range('A','E') as $columnID) {
            $sheet->getColumnDimension($columnID)
                ->setAutoSize(true);
        }

        // Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $objPHPExcel->setActiveSheetIndex(0);

        // Redirect output to a client’s web browser (Excel2007)
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment;filename="transaction_report.xlsx"');
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
        $objWriter->save('php://output');

        exit();
    } catch (Exception $e) {
        die('Error exporting data to Excel: ' . $e->getMessage());
    }
}

// Handle export based on format parameter
if (isset($_GET['format'])) {
    $format = $_GET['format'];

    // Perform export based on selected format
    if ($format == 'excel') {
        exportToExcel($conn);
    } else {
        // Handle other formats (e.g., PDF) if needed
        // Add more export functions for other formats as required
    }
} else {
    // Redirect back to reports page if format parameter is missing
    header("Location: reports.php");
    exit();
}

$conn->close();
?>
